create database ordersdb;

use ordersdb;

drop table IF EXISTS FILE_DETAILS;

CREATE TABLE FILE_DETAILS
(
  FILE_ID  INT PRIMARY KEY AUTO_INCREMENT,
  FILE_NAME VARCHAR(100)
);

drop table IF EXISTS ORDER_DETAILS;

CREATE TABLE ORDER_DETAILS
(
   ID INT NOT NULL,
   ORDERING_CURRENCY VARCHAR(20),
   TO_CURRENCY VARCHAR(20),
   TIMESTAMP VARCHAR(20),
   DEAL_AMOUNT FLOAT(15,2),
   FILE_NAME VARCHAR(100),
   PRIMARY KEY(ID)
);

drop table IF EXISTS INVALID_ORDERS;

CREATE TABLE INVALID_ORDERS
(
	FILE_NAME VARCHAR(100),
	INVALID_RECORD VARCHAR(250)
);

drop table IF EXISTS ORDER_CURRENCY_COUNT_DETAILS;

CREATE TABLE ORDER_CURRENCY_COUNT_DETAILS
(
	 ORDERING_CURRENCY VARCHAR(250),
     DEAL_COUNT FLOAT(15,2),
	 FILE_NAME VARCHAR(100)
);


